### ISSUE TITLE
Getting started tutorial of mesher has misspelled

### ISSUE THREAD

**Issue by SmartsYoung** [apache/servicecomb-website#225]
In the website of http://servicecomb.apache.org/cn/docs/mersher-quick-start/, the mesher has wrongly write in mersher. It's better to revise it.

**Comment by WillemJiang** [comment]
Do you mind send us a PR for it?  You can update the website from the below link on the page:

![image](https://user-images.githubusercontent.com/219644/69898444-aefb1700-1394-11ea-9fd3-f171d8fe45e7.png)

**Comment by yuyang-gif** [comment]
I am trying  to fix it

**Comment by zaneChou1** [comment]
@SmartsYoung this  issue was fixed  in https://github.com/apache/servicecomb-website/commit/a7d30655e48627769d79db3816756c8092847f15  and https://github.com/apache/servicecomb-website/commit/bf529ac16ac38b38c98335bdb261772e2a35b022. And you can close it.
