### ISSUE TITLE
官网好多链接都404了，建议更新一下

### ISSUE THREAD

**Issue by hwtayg** [apache/servicecomb-website#265]
比如 http://servicecomb.apache.org/cn/docs/open-design/

开源微服务框架 Apache ServiceComb 的前身为华为云的 微服务引擎 CSE (Cloud Service Engine) 云服务,

**Comment by WillemJiang** [comment]
@hwtayg I just checked,  the link is accessible.

**Comment by zhfeng** [comment]
@WillemJiang I think he was talking about the link inside of the document, just like [微服务引擎 CSE (Cloud Service Engine) 云服务](https://support.huaweicloud.com/usermanual-servicestage/zh-cn_topic_0053812706.html) which is broken,

**Comment by hwtayg** [comment]
是的，链接可以打开，但是内容啥都没有，提示 “很抱歉，地球我们都找遍了，还是没发现您要的页面”

**Comment by liubao68** [comment]
fixed.
